title: All Main Quest Extended

# The version of your route. There's no particular format here.
# This will be displayed in the metadata in the settings dialog
version: 1.0

# This is the route itself. Here it points to the main.yaml file we created earlier
route:
  use: ./main.yaml

# Extra configuration.
# The project must define a map to compile properly.
# For now, we will use the Breath of the Wild celer map maintained by Pistonight
config:
  - use: Pistonight/celer-presets/botw/full.yaml

  - icons:
      zelda: https://icons.pistonite.org/icon/character.zelda.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
      sor: https://icons.pistonite.org/icon/location.sor.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
      horse: https://icons.pistonite.org/icon/misc.horse.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
      daruk: https://icons.pistonite.org/icon/character.daruk.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
      shrine-active: https://icons.pistonite.org/icon/shrine.shrine.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
      guardian: https://icons.pistonite.org/icon/misc.flux_construct.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
      ruta: https://icons.pistonite.org/icon/location.ruta.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
      blight: https://icons.pistonite.org/icon/character.ganon.none.f24c99.ffc0fa.f24c99.ffc0fa.f24c99.ffc0fa.png
      SoR: https://icons.pistonite.org/icon/location.sor.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
      IST: https://icons.pistonite.org/icon/misc.apple.circle.8c5e28.ffffb5.8c5e28.ffffb5.8c5e28.ffffb5.png
      Fairy: https://icons.pistonite.org/icon/character.great_fairy.none.f24c99.ffc0fa.f24c99.ffc0fa.f24c99.ffc0fa.png
      village: https://icons.pistonite.org/icon/location.house.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
      medoh: https://icons.pistonite.org/icon/location.medoh.none.f24c99.ffc0fa.f24c99.ffc0fa.f24c99.ffc0fa.png
      blight: https://icons.pistonite.org/icon/character.ganon.none.f24c99.ffc0fa.f24c99.ffc0fa.f24c99.ffc0fa.png
      impa: https://icons.pistonite.org/icon/character.impa.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
      blue: https://icons.pistonite.org/icon/misc.flux_construct.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
      labo: https://icons.pistonite.org/icon/location.lab.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
      camera: https://icons.pistonite.org/icon/rune.camera.none.568c28.c8e6af.568c28.c8e6af.568c28.c8e6af.png
      tenu: https://icons.pistonite.org/icon/shrine.blessing.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
      kogha: https://icons.pistonite.org/icon/character.kohga.none.f24c99.ffc0fa.f24c99.ffc0fa.f24c99.ffc0fa.png
      naboris-not-finish: https://icons.pistonite.org/icon/location.naboris.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
      quest: https://icons.pistonite.org/icon/misc.double_square.none.cfa240.ffd700.8c5e28.fdfdfd.8c5e28.fdfdfd.png
      ruta-not-finish: https://icons.pistonite.org/icon/location.ruta.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
      Yunobo: https://icons.pistonite.org/icon/character.yunobo.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
      mine: https://icons.pistonite.org/icon/location.fire_temple.none.633830.f0673a.633830.f0673a.633830.f0673a.png
      pont: https://icons.pistonite.org/icon/location.skyview_tower.none.633830.f0673a.633830.f0673a.633830.f0673a.png
      rudania-not-finish: https://icons.pistonite.org/icon/location.rudania.none.8c5e28.ffffb5.8c5e28.ffffb5.8c5e28.ffffb5.png
      rudania: https://icons.pistonite.org/icon/location.rudania.none.f24c99.ffc0fa.f24c99.ffc0fa.f24c99.ffc0fa.png
      tétralame: https://icons.pistonite.org/icon/misc.hammer.none.cfa240.000000.cfa240.000000.cfa240.000000.png
      shrine-dlc: https://icons.pistonite.org/icon/shrine.dlc_shrine.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
      terminal: https://icons.pistonite.org/icon/shrine.dlc_shrine.none.8c5e28.ffffb5.8c5e28.ffffb5.8c5e28.ffffb5.png
      
  - plugins:
      - use: link
      - use: variables 